# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4b38d9aa6ad75c9822af80497ac8c0b1312cfa63b1a62b4119fce6c1cf3a92c9bdd87fccf1967d490b2ea11769b253369a3de1fec5b85a681600671b66e707

test:
  secret_key_base: d2196a3104f7a06a3519fa9a101db9bfa1432e597e5d6c6cd01c56d2e4346923692acb41d2ab44729104fe2526356d25e9f34b18a905c1bc30dc4b63d503513c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
